package de.neemann.digital.hdl.vhdl;

import de.neemann.digital.core.NodeException;
import de.neemann.digital.draw.elements.PinException;
import de.neemann.digital.draw.library.ElementNotFoundException;
import de.neemann.digital.integration.ToBreakRunner;
import junit.framework.TestCase;

import java.io.IOException;

public class ConstantTest extends TestCase {

    public void testSimple() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/const.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "USE ieee.numeric_std.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic;\n" +
                "    PORT_Y: out std_logic );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component XOR_GATE_2\n" +
                "    port (\n" +
                "      PORT_out: out std_logic;\n" +
                "      PORT_a: in std_logic;\n" +
                "      PORT_b: in std_logic );\n" +
                "  end component;\n" +
                "\n" +
                "  signal S0: std_logic;\n" +
                "begin\n" +
                "  S0 <= '0';\n" +
                "  gate0 : XOR_GATE_2\n" +
                "    port map (\n" +
                "      PORT_out => PORT_Y,\n" +
                "      PORT_a => PORT_A,\n" +
                "      PORT_b => S0 );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- XOR_GATE_2\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity XOR_GATE_2 is\n" +
                "  port (\n" +
                "    PORT_out: out std_logic;\n" +
                "    PORT_a: in std_logic;\n" +
                "    PORT_b: in std_logic );\n" +
                "end XOR_GATE_2;\n" +
                "\n" +
                "architecture XOR_GATE_2_arch of XOR_GATE_2 is\n" +
                "begin\n" +
                "  PORT_out <= PORT_a XOR PORT_b;\n" +
                "end XOR_GATE_2_arch;\n", vhdl);
    }

    public void testSimple2() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/const2.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "USE ieee.numeric_std.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic_vector (2 downto 0);\n" +
                "    PORT_Y: out std_logic_vector (2 downto 0) );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component XOR_GATE_BUS_2\n" +
                "    generic ( bitCount : integer );\n" +
                "    port (\n" +
                "      PORT_out: out std_logic_vector ((bitCount-1) downto 0);\n" +
                "      PORT_a: in std_logic_vector ((bitCount-1) downto 0);\n" +
                "      PORT_b: in std_logic_vector ((bitCount-1) downto 0) );\n" +
                "  end component;\n" +
                "\n" +
                "  signal S0: std_logic_vector (2 downto 0);\n" +
                "begin\n" +
                "  S0 <= std_logic_vector(to_unsigned(0,3));\n" +
                "  gate0 : XOR_GATE_BUS_2\n" +
                "    generic map ( bitCount => 3)\n" +
                "    port map (\n" +
                "      PORT_out => PORT_Y,\n" +
                "      PORT_a => PORT_A,\n" +
                "      PORT_b => S0 );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- XOR_GATE_BUS_2\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity XOR_GATE_BUS_2 is\n" +
                "  generic ( bitCount : integer );\n" +
                "  port (\n" +
                "    PORT_out: out std_logic_vector ((bitCount-1) downto 0);\n" +
                "    PORT_a: in std_logic_vector ((bitCount-1) downto 0);\n" +
                "    PORT_b: in std_logic_vector ((bitCount-1) downto 0) );\n" +
                "end XOR_GATE_BUS_2;\n" +
                "\n" +
                "architecture XOR_GATE_BUS_2_arch of XOR_GATE_BUS_2 is\n" +
                "begin\n" +
                "  PORT_out <= PORT_a XOR PORT_b;\n" +
                "end XOR_GATE_BUS_2_arch;\n", vhdl);
    }

}