package de.neemann.digital.hdl.vhdl;

import de.neemann.digital.core.NodeException;
import de.neemann.digital.draw.elements.PinException;
import de.neemann.digital.draw.library.ElementNotFoundException;
import de.neemann.digital.integration.ToBreakRunner;
import junit.framework.TestCase;

import java.io.IOException;

public class SplitterTest extends TestCase {

    public void testSimple() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/splitter.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic_vector (3 downto 0);\n" +
                "    PORT_B: in std_logic_vector (3 downto 0);\n" +
                "    PORT_Y: out std_logic_vector (2 downto 0);\n" +
                "    PORT_Z: out std_logic_vector (4 downto 0) );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  signal S0: std_logic_vector (7 downto 0);\n" +
                "begin\n" +
                "  S0(3 downto 0) <= PORT_A;\n" +
                "  S0(7 downto 4) <= PORT_B;\n" +
                "  PORT_Y <= S0(2 downto 0);\n" +
                "  PORT_Z <= S0(7 downto 3);\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n", vhdl);
    }
}
