package de.neemann.digital.hdl.vhdl.lib;

import de.neemann.digital.core.NodeException;
import de.neemann.digital.draw.elements.PinException;
import de.neemann.digital.draw.library.ElementNotFoundException;
import de.neemann.digital.hdl.model.HDLException;
import de.neemann.digital.hdl.model.HDLModel;
import de.neemann.digital.hdl.vhdl.VHDLExporter;
import de.neemann.digital.integration.ToBreakRunner;
import junit.framework.TestCase;

import java.io.IOException;

public class ClockTest extends TestCase {

    public void testClock() throws PinException, NodeException, ElementNotFoundException, IOException, HDLException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/Clock.dig");
        String vhdl = new VHDLExporter(br.getLibrary()) {
            @Override
            protected void fixClocks(HDLModel model) {
                model.integrateClocks(10);
            }
        }.export(br.getCircuit()).toString();

        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "USE ieee.numeric_std.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_Y0: out std_logic;\n" +
                "    PORT_Clk: in std_logic;\n" +
                "    PORT_A: in std_logic );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component XOR_GATE_2\n" +
                "    port (\n" +
                "      PORT_out: out std_logic;\n" +
                "      PORT_a: in std_logic;\n" +
                "      PORT_b: in std_logic );\n" +
                "  end component;\n" +
                "\n" +
                "  component DIG_simpleClockDivider\n" +
                "      generic ( bits : integer;\n" +
                "                maxCounter : integer );\n" +
                "      port (\n" +
                "        PORT_out: out std_logic;\n" +
                "        PORT_in: in std_logic );\n" +
                "  end component;\n" +
                "\n" +
                "  signal PORT_Y0_sig: std_logic;\n" +
                "  signal S0: std_logic;\n" +
                "begin\n" +
                "  PORT_Y0 <= PORT_Y0_sig;\n" +
                "  gate0 : XOR_GATE_2\n" +
                "    port map (\n" +
                "      PORT_out => PORT_Y0_sig,\n" +
                "      PORT_a => PORT_A,\n" +
                "      PORT_b => S0 );\n" +
                "  gate1 : DIG_simpleClockDivider\n" +
                "    generic map (\n" +
                "      bits => 22,\n" +
                "      maxCounter => 2500000 )\n" +
                "    port map (\n" +
                "      PORT_in => PORT_Clk,\n" +
                "      PORT_out => S0 );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- XOR_GATE_2\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity XOR_GATE_2 is\n" +
                "  port (\n" +
                "    PORT_out: out std_logic;\n" +
                "    PORT_a: in std_logic;\n" +
                "    PORT_b: in std_logic );\n" +
                "end XOR_GATE_2;\n" +
                "\n" +
                "architecture XOR_GATE_2_arch of XOR_GATE_2 is\n" +
                "begin\n" +
                "  PORT_out <= PORT_a XOR PORT_b;\n" +
                "end XOR_GATE_2_arch;\n" +
                "\n" +
                "-- DIG_simpleClockDivider\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "USE ieee.numeric_std.all;\n" +
                "USE ieee.std_logic_unsigned.all;\n" +
                "\n" +
                "entity DIG_simpleClockDivider is\n" +
                "    generic ( bits : integer;\n" +
                "              maxCounter : integer );\n" +
                "    port (\n" +
                "      PORT_out: out std_logic;\n" +
                "      PORT_in: in std_logic );\n" +
                "end DIG_simpleClockDivider;\n" +
                "\n" +
                "architecture DIG_simpleClockDivider_arch of DIG_simpleClockDivider is\n" +
                "  signal counter: std_logic_vector((bits-1) downto 0) := (others => '0');\n" +
                "  signal state: std_logic;\n" +
                "begin\n" +
                "  process (PORT_in)\n" +
                "  begin\n" +
                "    if rising_edge(PORT_in) then\n" +
                "       if counter = std_logic_vector(to_unsigned(maxCounter, bits)) then\n" +
                "          counter <= (others => '0');\n" +
                "          state <= NOT (state);\n" +
                "       else\n" +
                "          counter <= counter+1;\n" +
                "       end if;\n" +
                "    end if;\n" +
                "  end process;\n" +
                "  PORT_out <= state;\n" +
                "end DIG_simpleClockDivider_arch;\n", vhdl);
    }

}
