package de.neemann.digital.hdl.vhdl.lib;

import de.neemann.digital.core.NodeException;
import de.neemann.digital.draw.elements.PinException;
import de.neemann.digital.draw.library.ElementNotFoundException;
import de.neemann.digital.hdl.vhdl.VHDLExporter;
import de.neemann.digital.integration.ToBreakRunner;
import junit.framework.TestCase;

import java.io.IOException;

public class MultiplexerTest extends TestCase {

    public void testSimple() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/mux.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic;\n" +
                "    PORT_B: in std_logic;\n" +
                "    PORT_C: out std_logic;\n" +
                "    PORT_Sel: in std_logic );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component MUX_GATE_1\n" +
                "    port (\n" +
                "      PORT_out: out std_logic;\n" +
                "      PORT_sel: in std_logic;\n" +
                "      PORT_in_0: in std_logic;\n" +
                "      PORT_in_1: in std_logic );\n" +
                "  end component;\n" +
                "\n" +
                "begin\n" +
                "  gate0 : MUX_GATE_1\n" +
                "    port map ( PORT_out => PORT_C , PORT_sel => PORT_Sel , PORT_in_0 => PORT_A , PORT_in_1 => PORT_B );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- MUX_GATE_1\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity MUX_GATE_1 is\n" +
                "  port (\n" +
                "    PORT_out: out std_logic;\n" +
                "    PORT_sel: in std_logic;\n" +
                "    PORT_in_0: in std_logic;\n" +
                "    PORT_in_1: in std_logic );\n" +
                "end MUX_GATE_1;\n" +
                "\n" +
                "architecture MUX_GATE_1_arch of MUX_GATE_1 is\n" +
                "begin\n" +
                "  with PORT_sel select\n" +
                "    PORT_out <=\n" +
                "      PORT_in_0 when '0',\n" +
                "      PORT_in_1 when '1',\n" +
                "      '0' when others;\n" +
                "end MUX_GATE_1_arch;\n",vhdl);
    }

    public void testSimple2() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/mux2.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic;\n" +
                "    PORT_B: in std_logic;\n" +
                "    PORT_Y: out std_logic;\n" +
                "    PORT_Sel: in std_logic_vector (1 downto 0);\n" +
                "    PORT_C: in std_logic;\n" +
                "    PORT_D: in std_logic );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component MUX_GATE_2\n" +
                "    port (\n" +
                "      PORT_out: out std_logic;\n" +
                "      PORT_sel: in std_logic_vector (1 downto 0);\n" +
                "      PORT_in_0: in std_logic;\n" +
                "      PORT_in_1: in std_logic;\n" +
                "      PORT_in_2: in std_logic;\n" +
                "      PORT_in_3: in std_logic );\n" +
                "  end component;\n" +
                "\n" +
                "begin\n" +
                "  gate0 : MUX_GATE_2\n" +
                "    port map ( PORT_out => PORT_Y , PORT_sel => PORT_Sel , PORT_in_0 => PORT_A , PORT_in_1 => PORT_B , PORT_in_2 => PORT_C , PORT_in_3 => PORT_D );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- MUX_GATE_2\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity MUX_GATE_2 is\n" +
                "  port (\n" +
                "    PORT_out: out std_logic;\n" +
                "    PORT_sel: in std_logic_vector (1 downto 0);\n" +
                "    PORT_in_0: in std_logic;\n" +
                "    PORT_in_1: in std_logic;\n" +
                "    PORT_in_2: in std_logic;\n" +
                "    PORT_in_3: in std_logic );\n" +
                "end MUX_GATE_2;\n" +
                "\n" +
                "architecture MUX_GATE_2_arch of MUX_GATE_2 is\n" +
                "begin\n" +
                "  with PORT_sel select\n" +
                "    PORT_out <=\n" +
                "      PORT_in_0 when \"00\",\n" +
                "      PORT_in_1 when \"01\",\n" +
                "      PORT_in_2 when \"10\",\n" +
                "      PORT_in_3 when \"11\",\n" +
                "      '0' when others;\n" +
                "end MUX_GATE_2_arch;\n",vhdl);
    }

    public void testSimple3() throws IOException, ElementNotFoundException, PinException, NodeException {
        ToBreakRunner br = new ToBreakRunner("dig/hdl/mux3.dig");
        String vhdl = new VHDLExporter(br.getLibrary()).export(br.getCircuit()).toString();
        assertEquals("-- auto generated by Digital\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "\n" +
                "entity main is\n" +
                "  port (\n" +
                "    PORT_A: in std_logic_vector (3 downto 0);\n" +
                "    PORT_B: in std_logic_vector (3 downto 0);\n" +
                "    PORT_Y: out std_logic_vector (3 downto 0);\n" +
                "    PORT_Sel: in std_logic_vector (1 downto 0);\n" +
                "    PORT_C: in std_logic_vector (3 downto 0);\n" +
                "    PORT_D: in std_logic_vector (3 downto 0) );\n" +
                "end main;\n" +
                "\n" +
                "architecture main_arch of main is\n" +
                "\n" +
                "  component MUX_GATE_BUS_2\n" +
                "    generic ( bitCount : integer );\n" +
                "    port (\n" +
                "      PORT_sel: in std_logic_vector (1 downto 0);\n" +
                "      PORT_out: out std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "      PORT_in_0: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "      PORT_in_1: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "      PORT_in_2: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "      PORT_in_3: in std_logic_vector ( (bitCount-1)  downto 0) );\n" +
                "  end component;\n" +
                "\n" +
                "begin\n" +
                "  gate0 : MUX_GATE_BUS_2\n" +
                "    generic map ( bitCount => 4)\n" +
                "    port map ( PORT_out => PORT_Y , PORT_sel => PORT_Sel , PORT_in_0 => PORT_A , PORT_in_1 => PORT_B , PORT_in_2 => PORT_C , PORT_in_3 => PORT_D );\n" +
                "end main_arch;\n" +
                "\n" +
                "-- library components\n" +
                "\n" +
                "-- MUX_GATE_BUS_2\n" +
                "\n" +
                "LIBRARY ieee;\n" +
                "USE ieee.std_logic_1164.all;\n" +
                "USE ieee.numeric_std.all;\n" +
                "\n" +
                "entity MUX_GATE_BUS_2 is\n" +
                "  generic ( bitCount : integer );\n" +
                "  port (\n" +
                "    PORT_sel: in std_logic_vector (1 downto 0);\n" +
                "    PORT_out: out std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "    PORT_in_0: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "    PORT_in_1: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "    PORT_in_2: in std_logic_vector ( (bitCount-1)  downto 0);\n" +
                "    PORT_in_3: in std_logic_vector ( (bitCount-1)  downto 0) );\n" +
                "end MUX_GATE_BUS_2;\n" +
                "\n" +
                "architecture MUX_GATE_BUS_2_arch of MUX_GATE_BUS_2 is\n" +
                "begin\n" +
                "  with PORT_sel select\n" +
                "    PORT_out <=\n" +
                "      PORT_in_0 when \"00\",\n" +
                "      PORT_in_1 when \"01\",\n" +
                "      PORT_in_2 when \"10\",\n" +
                "      PORT_in_3 when \"11\",\n" +
                "      std_logic_vector(to_unsigned(0,bitCount)) when others;\n" +
                "end MUX_GATE_BUS_2_arch;\n",vhdl);
    }

}
